### ISSUE TITLE
Find a good dataset for benchmarking aggregate queries

### ISSUE THREAD

**Issue by andygrove** [datafusion-rs/datafusion#104]
Ideally I would like to find a real-world dataset that will fit on my 1TB SSD that I can run aggregate queries against and where the resulting aggregate data can easily fit in memory (small number of GB).

I would like to use these to benchmark against other solutions such as Apache Spark and PrestoDB.

**Comment by enplotz** [comment]
Maybe something like the [1.1 Billion Taxi Rides Benchmarks](http://tech.marksblogg.com/benchmarks.html) (real-world data from NYCs TLC)?

> The dataset itself has 1.1 billion records, 51 columns and takes up about 500 GB of disk space uncompressed.

**Comment by andygrove** [comment]
I've started on some simple benchmarks based on this dataset.

https://github.com/datafusion-rs/benchmarks
