### ISSUE TITLE
Add support for NULL values

### ISSUE THREAD

**Issue by andygrove** [datafusion-rs/datafusion#138]
- CSV reader
- Parquet reader
- min/max must respect nulls
- add IS NULL / IS NOT NULL predicates

**Comment by srenatus** [comment]
I think the CSV reader has been dealt with in #145, hasn't it?

**Comment by andygrove** [comment]
@srenatus Yes it has. thanks.

**Comment by andygrove** [comment]
well, it hasn't been handled for parquet but I will create new issue for that
