### ISSUE TITLE
Automate release process including creating tags in GitHub

### ISSUE THREAD

**Issue by mbesancon** [datafusion-rs/datafusion#159]
It look like datafusion has only one release on github, not matching the ones in the milestones nor on cargo. Are Github releases not used (anymore) for the project? If not, indicate it and maybe remove the only release present there :)

BTW looking forward to see this project grow

**Comment by andygrove** [comment]
Thanks, removed that one release for now. 

I need to automate the release process including tagging releases. I'll hijack this issue for that.

**Comment by mbesancon** [comment]
Have you checked the cargo tools for automatically building and publishing new releases (both Cargo and git)?
https://github.com/sunng87/cargo-release

**Comment by andygrove** [comment]
Thanks for the tip @mbesancon I have started using this now.

**Comment by mbesancon** [comment]
out of curiosity, are you doing direct github release or cargo-release?
