### ISSUE TITLE
Cannot copy and paste SQL into console

### ISSUE THREAD

**Issue by andygrove** [datafusion-rs/datafusion#163]
If I visit https://www.datafusion.rs/guides/getting-started-docker/and copy this sql ...

```sql
CREATE EXTERNAL TABLE uk_cities (city VARCHAR(100), lat DOUBLE, lng DOUBLE) 
STORED AS CSV WITHOUT HEADER ROW 
LOCATION '/opt/datafusion/data/uk_cities.csv';
```
... and paste it into the console (running in Docker), I get:

```
DataFusion Console
datafusion> CREATE EXTERNAL TABLE uk_cities (city VARCHAR(100), lat DOUBLE, lng DOUBLE) 
> TORED AS CSV WITHOUT HEADER ROW 
> OCATION '/opt/datafusion/data/uk_cities.csv';
Executing query ...
Error: ParserError("Expected \'STORED AS\' clause, found Some(Identifier(\"TORED\"))")
```

It looks the first character after a newline gets dropped somehow.

**Comment by srenatus** [comment]
Interesting bug. From [previous issues](https://github.com/redox-os/termion/search?utf8=%E2%9C%93&q=first+character&type=Issues), I'd suspect `liner`'s usage of `termion`, as nothing on the datafusion side looks too odd. (I don't completely understand the difference between the paste vs typing in manually, except that the *pasting is so much faster*.

**Comment by andygrove** [comment]
I wonder if it is worth trying the [rustyline](https://github.com/kkawakam/rustyline) crate instead. I will take a look at this when I get a chance.
