### ISSUE TITLE
is the project still alive?

### ISSUE THREAD

**Issue by AnirudhVyas** [datafusion-rs/datafusion#176]
Is the project still alive and is there a roadmap that I can follow to know when it will be distributed/ distributed processing ready?

**Comment by andygrove** [comment]
Yes, it is.

I have taken a break lately but am going to be getting back into it soon. However, as a solo effort this will never get where it needs to get to so it will take more contributors to make this really happen.

I am planning on updating the roadmap in the next couple of weeks along with a blog post to try and get people interested in contributing.
