### ISSUE TITLE
HDFS Support

### ISSUE THREAD

**Issue by andygrove** [datafusion-rs/datafusion#22]
This is the lowest common denominator for being to run some distributed workloads on existing Hadoop clusters.

There is no working pure Rust HDFS library unfortunately, so we'll probably have to start with this one which wraps a C library that wraps the Java client.

http://hyunsik.github.io/hdfs-rs/hdfs/index.html

**Comment by messense** [comment]
There is a native HDFS library in C++ I think?

https://github.com/Pivotal-Data-Attic/attic-c-hdfs-client

It seems to have been merged into https://github.com/apache/incubator-hawq/tree/master/depends/libhdfs3

A downstream fork: https://github.com/ContinuumIO/libhdfs3-downstream

**Comment by andygrove** [comment]
Also Arrow has a C++ HDFS client ... https://github.com/apache/arrow/tree/master/cpp/src/arrow/io

**Comment by andygrove** [comment]
parquet-rs are planning on adding HDFS support and it makes more sense for them to do it rather than adding support in DataFusion so I'm closing this issue now.
