### ISSUE TITLE
Implement efficient serialization of RecordBatch

### ISSUE THREAD

**Issue by andygrove** [datafusion-rs/datafusion#63]
In order to stream data between nodes and to efficiently swap data out to disk and store in a native format, it will be necessary to serialize to a binary format.

**Comment by mgxm** [comment]
[capnproto-rust](https://github.com/capnproto/capnproto-rust)

**Comment by andygrove** [comment]
Arrow uses FlatBuffers but the Rust port of FlatBuffers isn't ready yet. We might need to do something proprietary to serialize the arrow arrays in the meantime.

**Comment by andygrove** [comment]
I have started work on the Quiver file format for serializing Arrow Arrays.
