### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by garro95** [datafusion-rs/datafusion#96]
The API documentation for this awesome project is very scarce, and this is a pity because a good documentation is the starting point for a wide adoption.
In my opinion there should be at least the crate-level documentation describing the project and how to use the framework.

**Comment by andygrove** [comment]
I totally agree. Unfortunately docs.rs can't host the docs because the project depends on thrift now.
I have published the current API docs manually here: https://datafusion.rs/docs/datafusion/

But now I need to start writing some documentation for all the structs / traits / methods etc ...

**Comment by messense** [comment]
I think https://github.com/sunchao/parquet-rs/pull/82 should make docs.rs work for datafusion?

**Comment by andygrove** [comment]
Documentation is now published here with each release:

https://datafusion.rs/docs/datafusion/index.html
